# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import bidi_pb2 as bidi__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bidi_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BidiServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStreamMessages = channel.stream_stream(
                '/bidirectional.BidiService/GetStreamMessages',
                request_serializer=bidi__pb2.InitialRequest.SerializeToString,
                response_deserializer=bidi__pb2.InitialResponse.FromString,
                _registered_method=True)
        self.GetSessionData = channel.stream_stream(
                '/bidirectional.BidiService/GetSessionData',
                request_serializer=bidi__pb2.InitialSessionRequest.SerializeToString,
                response_deserializer=bidi__pb2.InitialResponse.FromString,
                _registered_method=True)


class BidiServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetStreamMessages(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionData(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BidiServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStreamMessages': grpc.stream_stream_rpc_method_handler(
                    servicer.GetStreamMessages,
                    request_deserializer=bidi__pb2.InitialRequest.FromString,
                    response_serializer=bidi__pb2.InitialResponse.SerializeToString,
            ),
            'GetSessionData': grpc.stream_stream_rpc_method_handler(
                    servicer.GetSessionData,
                    request_deserializer=bidi__pb2.InitialSessionRequest.FromString,
                    response_serializer=bidi__pb2.InitialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bidirectional.BidiService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('bidirectional.BidiService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BidiService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStreamMessages(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bidirectional.BidiService/GetStreamMessages',
            bidi__pb2.InitialRequest.SerializeToString,
            bidi__pb2.InitialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessionData(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/bidirectional.BidiService/GetSessionData',
            bidi__pb2.InitialSessionRequest.SerializeToString,
            bidi__pb2.InitialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
