# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: bidi.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'bidi.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbidi.proto\x12\rbidirectional\x1a\x1fgoogle/protobuf/timestamp.proto\"*\n\x15InitialSessionRequest\x12\x11\n\tsessionId\x18\x01 \x01(\t\"\xb2\x01\n\x0eInitialRequest\x12\x14\n\x0csourceSystem\x18\x01 \x01(\t\x12\x33\n\x0fpublicationTime\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tsessionId\x18\x03 \x01(\t\x12\x11\n\tmessageId\x18\x04 \x01(\t\x12\x13\n\x0bmessageText\x18\x05 \x01(\t\x12\x1a\n\x12messageWithContext\x18\x06 \x01(\t\"m\n\x0fInitialResponse\x12)\n\x07success\x18\x01 \x01(\x0b\x32\x16.bidirectional.SuccessH\x00\x12%\n\x05\x65rror\x18\x02 \x01(\x0b\x32\x14.bidirectional.ErrorH\x00\x42\x08\n\x06result\"\x17\n\x07Success\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\"B\n\x05\x45rror\x12\x13\n\x0b\x64\x65scription\x18\x01 \x01(\t\x12\x11\n\terrorCode\x18\x02 \x01(\x05\x12\x11\n\terrorType\x18\x03 \x01(\t2\xc1\x01\n\x0b\x42idiService\x12V\n\x11GetStreamMessages\x12\x1d.bidirectional.InitialRequest\x1a\x1e.bidirectional.InitialResponse(\x01\x30\x01\x12Z\n\x0eGetSessionData\x12$.bidirectional.InitialSessionRequest\x1a\x1e.bidirectional.InitialResponse(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'bidi_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_INITIALSESSIONREQUEST']._serialized_start=62
  _globals['_INITIALSESSIONREQUEST']._serialized_end=104
  _globals['_INITIALREQUEST']._serialized_start=107
  _globals['_INITIALREQUEST']._serialized_end=285
  _globals['_INITIALRESPONSE']._serialized_start=287
  _globals['_INITIALRESPONSE']._serialized_end=396
  _globals['_SUCCESS']._serialized_start=398
  _globals['_SUCCESS']._serialized_end=421
  _globals['_ERROR']._serialized_start=423
  _globals['_ERROR']._serialized_end=489
  _globals['_BIDISERVICE']._serialized_start=492
  _globals['_BIDISERVICE']._serialized_end=685
# @@protoc_insertion_point(module_scope)
